name: PluginPacks
author: TobyDev265
version: 1.2.2
description: Install plugin packs for your server
depend: Sheep
api: [3.0.0]
main: TobyDev265\PluginPacks\Main

commands:
  pluginpacks:
    description: Install plugin packs
